name: Pinact Check

on:
  pull_request:
    paths:
      - .github/workflows/*

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag: v6.0.2
        with:
          show-progress: false

      - uses: suzuki-shunsuke/pinact-action@3132770ecce73073bcd618342c7f4092ed2f994c # tag: v3.0.0
        with:
          fix: "false"
          verify: "true"
          verify_min_age: "true"
          review: "true"
